import:
  - catalog/_defaults
  - catalog/azure/base/resource-group
  - catalog/azure/base/network
  - catalog/azure/aks/cluster

vars:
  stage: "prod"
  namespace: "platform"
  k8s:
    node_count: 3
    cluster_version: "1.29"
