apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka.name }}
spec:
  kafka:
    version: {{ .Values.kafka.kafkaVersion | quote }}
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      process.roles: broker,controller
      node.id: 0
      controller.quorum.voters: "0@{{ .Values.kafka.name }}-kafka-0.{{ .Values.kafka.name }}-kafka-brokers.dev.svc:9094,1@{{ .Values.kafka.name }}-kafka-1.{{ .Values.kafka.name }}-kafka-brokers.dev.svc:9094,2@{{ .Values.kafka.name }}-kafka-2.{{ .Values.kafka.name }}-kafka-brokers.dev.svc:9094"
      inter.broker.listener.name: tls
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    storage:
      type: persistent-claim
      size: {{ .Values.kafka.storage.size }}
      deleteClaim: false
    # Porta 9094 do KRaft é interna (controller), Strimzi cria service headless
    kraft:
      enabled: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
