apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Values.user.name }}
  labels:
    strimzi.io/cluster: {{ .Values.kafka.name }}
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: {{ .Values.topic.name }}
          patternType: literal
        operation: Write
      - resource:
          type: topic
          name: {{ .Values.topic.name }}
          patternType: literal
        operation: Create
      - resource:
          type: topic
          name: {{ .Values.topic.name }}
          patternType: literal
        operation: Describe
