repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: rancher-latest
    url: https://releases.rancher.com/server-charts/latest

bases: []

releases:
  - name: namespaces
    namespace: kube-system
    chart: "https://github.com/helm/chart-testing/releases/download/v3.10.1/kubectl.tgz"
    version: "3.10.1"
    hooks:
      - events: ["postsync"]
        showlogs: true
    installed: true
    # truque simples: aplicar namespaces via hooks não é nativo do helmfile; você pode usar 'helmfile hooks' ou aplicar com Makefile antes

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.15.3
    createNamespace: true
    values:
      - installCRDs: true

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.11.2
    createNamespace: true
    values:
      - controller:
          admissionWebhooks:
            enabled: true

  - name: rancher
    namespace: cattle-system
    chart: rancher-latest/rancher
    version: 2.9.2
    createNamespace: true
    values:
      - hostname: "{{ .Values.rancher.hostname | default \"rancher.127.0.0.1.nip.io\" }}"
        bootstrapPassword: "{{ .Values.rancher.bootstrapPassword | default \"Admin12345!\" }}"
        replicas: 1
        ingress:
          tls:
            source: "rancher"
