import:
  - catalog/_defaults
  - catalog/azure/base/resource-group
  - catalog/azure/base/network
  - catalog/azure/aks/cluster

vars:
  stage: "hml"
  namespace: "platform"
  k8s:
    node_count: 2
