- hosts: local
  vars_files: ["../group_vars/all.yml"]
  tasks:
    - name: ClusterIssuer Let's Encrypt HTTP-01
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: letsencrypt
          spec:
            acme:
              email: "{{ email_le }}"
              server: https://acme-v02.api.letsencrypt.org/directory
              privateKeySecretRef:
                name: letsencrypt
              solvers:
                - http01:
                    ingress:
                      class: nginx