# stacks/ue2/dev/stack.yaml (FLAT, sem imports)
vars:
  stage: "dev"
  namespace: "platform"

  azure:
    location: "eastus2"
    subscription_id: "b171271a-b25e-45aa-ad46-f48535580096"   # <<< ajuste
    tenant_id: "b5306433-1086-417b-83c5-12287dd97f69"               # <<< ajuste

  k8s:
    cluster_version: "1.29"
    node_size: "Standard_D4s_v5"
    node_count: 2

  rancher:
    hostname: "rancher-dev.127.0.0.1.nip.io"      # <<< ajuste se tiver domínio
    bootstrapPassword: "Admin12345!"              # <<< ajuste

  gitops:
    repo_url: "https://github.com/Danylo93/devops-rancher-azure-atmos.git" # <<< ajuste
    target_revision: "main"
    path_root: "gitops"
    argocd:
      hostname: "argocd-dev.127.0.0.1.nip.io"     # <<< ajuste

components:
  terraform:
    azure/resource-group:
      vars:
        rg_name: "rg-{{ var.namespace }}-{{ var.stage }}"
        location: "{{ var.azure.location }}"
        subscription_id: "{{ var.azure.subscription_id }}"
        tenant_id: "{{ var.azure.tenant_id }}"

    azure/network:
      vars:
        rg_name: "rg-{{ var.namespace }}-{{ var.stage }}"
        location: "{{ var.azure.location }}"
        vnet_name: "vnet-{{ var.namespace }}-{{ var.stage }}"
        address_space: "10.40.0.0/16"
        aks_subnet_name: "snet-aks"
        aks_subnet_prefix: "10.40.1.0/24"

    azure/aks:
      vars:
        rg_name: "rg-{{ var.namespace }}-{{ var.stage }}"
        location: "{{ var.azure.location }}"
        cluster_name: "aks-{{ var.namespace }}-{{ var.stage }}"
        kubernetes_version: "{{ var.k8s.cluster_version }}"
        node_vm_size: "{{ var.k8s.node_size }}"
        node_count: "{{ var.k8s.node_count }}"
        # Se o módulo exigir 'aks_subnet_id', você pode:
        # - rodar o apply da network e depois preencher aqui manualmente, OU
        # - ajustar o módulo para buscar por nome (data) e não exigir o ID explícito.

  helmfile:
    base:
      vars:
        rancher:
          hostname: "{{ var.rancher.hostname }}"
          bootstrapPassword: "{{ var.rancher.bootstrapPassword }}"
    dev:
      vars: {}
    gitops:
      vars:
        gitops:
          repo_url: "{{ var.gitops.repo_url }}"
          target_revision: "{{ var.gitops.target_revision }}"
          path_root: "{{ var.gitops.path_root }}"
          argocd:
            hostname: "{{ var.gitops.argocd.hostname }}"
