apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: app
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-prod-kafka-bootstrap.prod.svc:9092"
